version: "1"

services:
  yt-mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: mssqlserver       
    restart: always
    hostname: mssql
    environment:
      SA_PASSWORD: Password123          
      ACCEPT_EULA: Y

    volumes:
      - mssqlvolume:/var/opt/mssql/data 
      - ./bk:/var/opt/mssql/backup      
    ports:
      - "1433:1433"                

volumes:
    mssqlvolume:
